import type { Project, Service, TeamMember, FAQItem, SiteSettings, HomeContent } from './types';

export const mockProjects: Project[] = [
  {
    id: '1',
    title: 'Hoofdkantoor TechForward Amsterdam',
    slug: 'techforward-amsterdam',
    sector: 'Technologie',
    featured: true,
    heroImage: {
      id: 'm1',
      url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1920&q=80',
      alt: 'Modern kantoorinrichting TechForward Amsterdam',
      filename: 'techforward-hero.jpg',
    },
    gallery: [
      { image: { id: 'm1a', url: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1200&q=80', alt: 'Open werkruimte', filename: 'tw-1.jpg' } },
      { image: { id: 'm1b', url: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1200&q=80', alt: 'Vergaderruimte', filename: 'tw-2.jpg' } },
      { image: { id: 'm1c', url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1200&q=80', alt: 'Lounge zone', filename: 'tw-3.jpg' } },
      { image: { id: 'm1d', url: 'https://images.unsplash.com/photo-1604328698692-f76ea9498e76?w=1200&q=80', alt: 'Directiekantoor', filename: 'tw-4.jpg' } },
    ],
    summary: 'Volledige herinrichting van 3.200 m² kantoorruimte voor een snelgroeiend technologiebedrijf, met focus op collaboratief werken en welzijn van medewerkers.',
    specs: { size: '3.200 m²', duration: '14 weken', workplaces: '240 werkplekken', year: 2024 },
    testimonial: {
      quote: 'DM Kantoorinrichtingen heeft onze visie op de toekomst van werk perfect vertaald naar een ruimte die onze teams inspireert en motiveert.',
      author: 'Jeroen van der Berg',
      role: 'CEO TechForward',
    },
    resultMetric: { label: 'Hogere medewerkerstevredenheid', value: '43%' },
    createdAt: '2024-11-01T00:00:00.000Z',
    updatedAt: '2024-11-01T00:00:00.000Z',
  },
  {
    id: '2',
    title: 'Zorgcentrum De Linde Utrecht',
    slug: 'zorgcentrum-de-linde',
    sector: 'Zorg',
    featured: true,
    heroImage: {
      id: 'm2',
      url: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1920&q=80',
      alt: 'Zorgcentrum inrichting',
      filename: 'linde-hero.jpg',
    },
    gallery: [
      { image: { id: 'm2a', url: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=1200&q=80', alt: 'Wachtkamer', filename: 'linde-1.jpg' } },
      { image: { id: 'm2b', url: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?w=1200&q=80', alt: 'Kantoorruimte', filename: 'linde-2.jpg' } },
    ],
    summary: 'Ergonomische herinrichting van kantoor- en spreekkamers voor een modern zorgcentrum, met zorgvuldige aandacht voor patiëntcomfort en werkpleggezondheid.',
    specs: { size: '1.800 m²', duration: '8 weken', workplaces: '95 werkplekken', year: 2024 },
    testimonial: {
      quote: 'Onze medewerkers zijn veel gezonder en gelukkiger op het werk. De ergonomische werkplekken hebben het ziekteverzuim al in het eerste kwartaal merkbaar teruggebracht.',
      author: 'Dr. Sandra Visser',
      role: 'Directeur De Linde',
    },
    resultMetric: { label: 'Reductie ziekteverzuim', value: '31%' },
    createdAt: '2024-09-01T00:00:00.000Z',
    updatedAt: '2024-09-01T00:00:00.000Z',
  },
  {
    id: '3',
    title: 'Advocatenkantoor Vermeer & Partners Den Haag',
    slug: 'vermeer-partners-den-haag',
    sector: 'Zakelijke Dienstverlening',
    featured: false,
    heroImage: {
      id: 'm3',
      url: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=1920&q=80',
      alt: 'Stijlvol advocatenkantoor',
      filename: 'vermeer-hero.jpg',
    },
    gallery: [
      { image: { id: 'm3a', url: 'https://images.unsplash.com/photo-1505409628601-edc9af17fda6?w=1200&q=80', alt: 'Vergaderzaal', filename: 'vermeer-1.jpg' } },
      { image: { id: 'm3b', url: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=1200&q=80', alt: 'Teamoverleg', filename: 'vermeer-2.jpg' } },
    ],
    summary: 'Premium kantoorinrichting voor een gerenommeerd advocatenkantoor, waarbij traditie en moderniteit hand in hand gaan voor een optimale werkomgeving.',
    specs: { size: '950 m²', duration: '6 weken', workplaces: '55 werkplekken', year: 2023 },
    testimonial: {
      quote: 'De sfeer van ons nieuwe kantoor straalt precies de professionaliteit en betrouwbaarheid uit die wij onze cliënten willen bieden.',
      author: 'Mr. Eline Vermeer',
      role: 'Managing Partner',
    },
    resultMetric: { label: 'Hogere klanttevredenheid', value: '28%' },
    createdAt: '2023-12-01T00:00:00.000Z',
    updatedAt: '2023-12-01T00:00:00.000Z',
  },
  {
    id: '4',
    title: 'Hogeschool Horizon Rotterdam',
    slug: 'hogeschool-horizon-rotterdam',
    sector: 'Onderwijs',
    featured: false,
    heroImage: {
      id: 'm4',
      url: 'https://images.unsplash.com/photo-1562774053-701939374585?w=1920&q=80',
      alt: 'Moderne onderwijsomgeving',
      filename: 'horizon-hero.jpg',
    },
    gallery: [
      { image: { id: 'm4a', url: 'https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=1200&q=80', alt: 'Studielandschap', filename: 'horizon-1.jpg' } },
      { image: { id: 'm4b', url: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?w=1200&q=80', alt: 'Docentenwerkplek', filename: 'horizon-2.jpg' } },
    ],
    summary: 'Flexibele en inspirerende inrichting van docenten- en administratieve werkruimtes voor een toonaangevende hogeschool in Rotterdam.',
    specs: { size: '2.100 m²', duration: '10 weken', workplaces: '180 werkplekken', year: 2023 },
    testimonial: {
      quote: 'De nieuwe werkruimtes stimuleren samenwerking tussen docenten en hebben onze administratieve processen enorm verbeterd.',
      author: 'Petra Konings',
      role: 'Rector Hogeschool Horizon',
    },
    resultMetric: { label: 'Productiviteitsverbetering', value: '37%' },
    createdAt: '2023-08-01T00:00:00.000Z',
    updatedAt: '2023-08-01T00:00:00.000Z',
  },
  {
    id: '5',
    title: 'Provincie Noord-Holland Haarlem',
    slug: 'provincie-noord-holland-haarlem',
    sector: 'Overheid',
    featured: true,
    heroImage: {
      id: 'm5',
      url: 'https://images.unsplash.com/photo-1568992687947-868a62a9f521?w=1920&q=80',
      alt: 'Provinciehuis kantoorinrichting',
      filename: 'provincie-hero.jpg',
    },
    gallery: [
      { image: { id: 'm5a', url: 'https://images.unsplash.com/photo-1554469384-e58fac16e23a?w=1200&q=80', alt: 'Werkzone', filename: 'provincie-1.jpg' } },
      { image: { id: 'm5b', url: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=1200&q=80', alt: 'Vergaderruimte', filename: 'provincie-2.jpg' } },
    ],
    summary: 'Duurzame en circulaire herinrichting van het provinciehuis, met hergebruik van 70% van het bestaande meubilair en BREEAM-certificering als doelstelling.',
    specs: { size: '4.800 m²', duration: '18 weken', workplaces: '380 werkplekken', year: 2024 },
    testimonial: {
      quote: 'DM Kantoorinrichtingen begreep als geen ander dat duurzaamheid bij ons niet alleen een wens is, maar een verplichting.',
      author: 'Annemarie de Wit',
      role: 'Facilitair Manager Provincie NH',
    },
    resultMetric: { label: 'Lagere CO₂-uitstoot vs. nieuwbouw', value: '62%' },
    createdAt: '2024-06-01T00:00:00.000Z',
    updatedAt: '2024-06-01T00:00:00.000Z',
  },
  {
    id: '6',
    title: 'Ontwerpstudio Studio Tangram Amsterdam',
    slug: 'studio-tangram-amsterdam',
    sector: 'Creatief',
    featured: false,
    heroImage: {
      id: 'm6',
      url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1920&q=80',
      alt: 'Creatieve werkruimte Studio Tangram',
      filename: 'tangram-hero.jpg',
    },
    gallery: [
      { image: { id: 'm6a', url: 'https://images.unsplash.com/photo-1541746972996-4e0b0f43e02a?w=1200&q=80', alt: 'Makerspace', filename: 'tangram-1.jpg' } },
      { image: { id: 'm6b', url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&q=80', alt: 'Teamtafel', filename: 'tangram-2.jpg' } },
    ],
    summary: 'Creatieve en inspirerende werkomgeving voor een multidisciplinair ontwerpbureau, met ruimte voor presentaties, makerspace en teamoverleg.',
    specs: { size: '680 m²', duration: '7 weken', workplaces: '32 werkplekken', year: 2023 },
    testimonial: {
      quote: 'Ze dachten écht met ons mee. Het resultaat is geen kantoor dat op ons is geplakt — het is ons kantoor.',
      author: 'Fleur Bosman',
      role: 'Creative Director Studio Tangram',
    },
    resultMetric: { label: 'Medewerkerstevredenheid werkplek', value: '9.2' },
    createdAt: '2023-05-01T00:00:00.000Z',
    updatedAt: '2023-05-01T00:00:00.000Z',
  },
];

export const mockServices: Service[] = [
  {
    id: 's1',
    title: 'Strategisch Advies',
    slug: 'strategisch-advies',
    shortDescription: 'We analyseren uw werkcultuur, doelstellingen en ruimte om een integraal inrichtingsplan te maken dat uw organisatie écht vooruit helpt.',
    icon: 'Target',
    heroImage: { id: 'sm1', url: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1920&q=80', alt: 'Strategisch adviesgesprek', filename: 'advies-hero.jpg' },    features: [
      { icon: 'Users', title: 'Werkplekanalyse', description: 'Grondig onderzoek naar werkpatronen en ruimtegebruik binnen uw organisatie.' },
      { icon: 'Layout', title: 'Programma van Eisen', description: 'Vertaling van uw wensen en behoeften naar concrete specificaties.' },
      { icon: 'Target', title: 'Strategisch Masterplan', description: 'Langetermijnvisie voor uw kantooromgeving afgestemd op uw groeistrategie.' },
      { icon: 'Lightbulb', title: 'Change Management', description: 'Begeleiding van medewerkers bij de transitie naar nieuwe werkwijzen.' },
    ],
    benefits: [{ text: 'Hogere medewerkerstevredenheid' }, { text: 'Efficiënter ruimtegebruik' }, { text: 'Lagere huisvestingskosten' }, { text: 'Toekomstbestendig plan' }],
    order: 1,
  },
  {
    id: 's2',
    title: 'Ergonomisch Ontwerp',
    slug: 'ergonomisch-ontwerp',
    shortDescription: 'Gezonde werkplekken die ziekteverzuim verminderen en productiviteit verhogen. Wij zijn gecertificeerde ergonomie-adviseurs.',
    icon: 'Heart',
    heroImage: { id: 'sm2', url: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=1920&q=80', alt: 'Ergonomische werkplek', filename: 'ergonomie-hero.jpg' },
    features: [
      { icon: 'Heart', title: 'Ergonomische Screening', description: 'Individuele beoordeling van werkhoudingen en belasting.' },
      { icon: 'Monitor', title: 'Zit-sta Werkplekken', description: 'Dynamische werkplekken die beweging stimuleren.' },
      { icon: 'Lightbulb', title: 'Verlichting & Akoestiek', description: 'Optimale licht- en geluidsomstandigheden voor concentratie.' },
      { icon: 'ShieldCheck', title: 'Arbo-certificering', description: 'Volledig voldoen aan Arbo-wetgeving en NEN-normen.' },
    ],
    benefits: [{ text: 'Minder ziekteverzuim' }, { text: 'Betere concentratie' }, { text: 'Arbo-conform' }, { text: 'Hogere medewerkerstevredenheid' }],
    order: 2,
  },
  {
    id: 's3',
    title: 'Interieurdesign',
    slug: 'interieurdesign',
    shortDescription: 'Van concept tot realisatie: wij ontwerpen kantooromgevingen die uw merkidentiteit versterken en medewerkers inspireren.',
    icon: 'Pencil',
    heroImage: { id: 'sm3', url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1920&q=80', alt: 'Interieurdesign kantoor', filename: 'design-hero.jpg' },
    features: [
      { icon: 'Pencil', title: 'Conceptontwikkeling', description: 'Creatieve visie die aansluit bij uw merkwaarden en cultuur.' },
      { icon: 'Layout', title: '3D Visualisaties', description: 'Realistisch beeld van het eindresultaat voor definitieve keuzes.' },
      { icon: 'Zap', title: 'Materialenadvies', description: 'Duurzame en esthetisch verantwoorde keuzes voor vloer, wand en plafond.' },
      { icon: 'Hammer', title: 'Projectmanagement', description: 'Volledige coördinatie van aannemers, leveranciers en installateurs.' },
    ],
    benefits: [{ text: 'Sterk werkgeversmerk' }, { text: 'Inspirerende werksfeer' }, { text: 'Duurzame materialenkeuze' }, { text: 'Tijdige oplevering' }],
    order: 3,
  },
  {
    id: 's4',
    title: 'Projectinrichting',
    slug: 'projectinrichting',
    shortDescription: 'Volledige levering en plaatsing van kantoormeubilair van top-A-merken, met garantie en nazorg voor de lange termijn.',
    icon: 'Hammer',
    heroImage: { id: 'sm4', url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1920&q=80', alt: 'Kantoormeubilair plaatsing', filename: 'inrichting-hero.jpg' },
    features: [
      { icon: 'Hammer', title: 'A-merk Meubilair', description: 'Exclusief partner van Vitra, Herman Miller, Ahrend en Kinnarps.' },
      { icon: 'ShieldCheck', title: 'Garantie & Service', description: 'Uitgebreide garanties en snel serviceonderhoud.' },
      { icon: 'Zap', title: 'Snelle Levering', description: 'Strakke planningen met minimale verstoring van uw bedrijfsvoering.' },
      { icon: 'Users', title: 'Installatie & Instructie', description: 'Professionele montage en gebruikerstraining.' },
    ],
    benefits: [{ text: 'Top-A merken' }, { text: 'Uitgebreide garantie' }, { text: 'Snelle levering' }, { text: 'Minimale overlast' }],
    order: 4,
  },
  {
    id: 's5',
    title: 'Duurzaamheid & Circulariteit',
    slug: 'duurzaamheid-circulariteit',
    shortDescription: 'Wij helpen u een kantooromgeving te creëren die bijdraagt aan uw ESG-doelstellingen en CO₂-reductie.',
    icon: 'Leaf',
    heroImage: { id: 'sm5', url: 'https://images.unsplash.com/photo-1542601906897-a9b4c1116f99?w=1920&q=80', alt: 'Duurzame kantoorinrichting', filename: 'duurzaam-hero.jpg' },
    features: [
      { icon: 'Leaf', title: 'Circulair Hergebruik', description: 'Bestaand meubilair opknappen, hergebruiken of verantwoord verwerken.' },
      { icon: 'ShieldCheck', title: 'BREEAM & WELL', description: 'Ondersteuning bij duurzaamheidscertificering van uw pand.' },
      { icon: 'Target', title: 'CO₂-rapportage', description: 'Meetbare impact van uw inrichtingskeuzes op het milieu.' },
      { icon: 'Users', title: 'Leveranciersketen', description: 'Uitsluitend partners met aantoonbaar duurzaamheidsbeleid.' },
    ],
    benefits: [{ text: 'ESG-doelstellingen halen' }, { text: 'Kostenbesparing via hergebruik' }, { text: 'Sterker werkgeversmerk' }, { text: 'Meetbare CO₂-reductie' }],
    order: 5,
  },
  {
    id: 's6',
    title: 'Hybride Werkplek',
    slug: 'hybride-werkplek',
    shortDescription: 'Flexibele kantooromgevingen die optimaal werken voor thuiswerkers, deeltijdmedewerkers en internationale teams.',
    icon: 'Monitor',
    heroImage: { id: 'sm6', url: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=1920&q=80', alt: 'Hybride werkplek setup', filename: 'hybride-hero.jpg' },
    features: [
      { icon: 'Monitor', title: 'Activity Based Working', description: 'Verschillende zones voor concentratie, samenwerking en informeel overleg.' },
      { icon: 'Zap', title: 'Technologie-integratie', description: 'Naadloze AV- en videoconferentie-oplossingen in elke ruimte.' },
      { icon: 'Layout', title: 'Desk Booking', description: 'Slimme systemen voor werkplekbeheer en -reservering.' },
      { icon: 'Users', title: 'Cultuurverandering', description: 'Begeleiding bij de overgang naar activiteitsgericht werken.' },
    ],
    benefits: [{ text: 'Optimale ruimtebenutting' }, { text: 'Tevreden hybride teams' }, { text: 'Toekomstbestendig' }, { text: 'Lagere m² kosten' }],
    order: 6,
  },
];

export const mockTeamMembers: TeamMember[] = [
  { id: 't1', name: 'Dirk Martens', role: 'Oprichter & Directeur', photo: { id: 'tp1', url: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&q=80', alt: 'Dirk Martens', filename: 'dirk.jpg' }, order: 1 },
  { id: 't2', name: 'Lisa van den Berg', role: 'Senior Interieurdesigner', photo: { id: 'tp2', url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80', alt: 'Lisa van den Berg', filename: 'lisa.jpg' }, order: 2 },
  { id: 't3', name: 'Mark Jansen', role: 'Ergonomie Specialist', photo: { id: 'tp3', url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80', alt: 'Mark Jansen', filename: 'mark.jpg' }, order: 3 },
  { id: 't4', name: 'Sophie de Groot', role: 'Projectmanager', photo: { id: 'tp4', url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=80', alt: 'Sophie de Groot', filename: 'sophie.jpg' }, order: 4 },
  { id: 't5', name: 'Tom Willems', role: 'Adviseur Hybride Werken', photo: { id: 'tp5', url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80', alt: 'Tom Willems', filename: 'tom.jpg' }, order: 5 },
  { id: 't6', name: 'Noor Bakker', role: 'Duurzaamheidsadviseur', photo: { id: 'tp6', url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80', alt: 'Noor Bakker', filename: 'noor.jpg' }, order: 6 },
];

export const mockFAQItems: FAQItem[] = [
  { id: 'f1', question: 'Hoe lang duurt een kantoorinrichtingsproject gemiddeld?', answer: 'De doorlooptijd hangt sterk af van de schaal van het project. Een kleinere inrichting van 200–500 m² realiseren wij doorgaans in 4 tot 6 weken. Grotere projecten van 2.000 m² of meer nemen 10 tot 16 weken in beslag, inclusief adviestraject, ontwerp en oplevering.', order: 1 },
  { id: 'f2', question: 'Werken jullie ook samen met onze architect of aannemer?', answer: 'Absoluut. Wij zijn gewend om als onderdeel van een groter bouwteam te opereren. We stemmen onze werkzaamheden nauw af met architecten, aannemers, installateurs en facilitair managers om een naadloos eindresultaat te garanderen.', order: 2 },
  { id: 'f3', question: 'Kunnen jullie bestaand meubilair hergebruiken of opknappen?', answer: 'Ja, duurzaamheid staat bij ons centraal. We beoordelen uw huidige inventaris op kwaliteit en bruikbaarheid. Goed meubilair knappen we op, passen we aan of integreren we in het nieuwe ontwerp. Wat niet meer bruikbaar is, verwerken we via onze circulaire partners.', order: 3 },
  { id: 'f4', question: "In welke regio's zijn jullie actief?", answer: "Vanuit ons hoofdkantoor in Buurmalsen werken wij door heel Nederland. Grote projecten realiseerden wij onder meer in Amsterdam, Utrecht, Rotterdam, Den Haag en Eindhoven. Ook voor projecten buiten Nederland — met name België en Duitsland — beschikken wij over de nodige ervaring.", order: 4 },
  { id: 'f5', question: 'Bieden jullie garantie en nazorg na oplevering?', answer: 'Alle meubilair die wij leveren heeft minimaal 5 jaar fabrieksgarantie. Daarnaast bieden wij 12 maanden nazorg: bij storingen of vragen komt ons serviceteam binnen 48 uur ter plaatse. Voor grotere klanten hebben wij ook meerjarige onderhoudscontracten beschikbaar.', order: 5 },
];

export const mockSiteSettings: SiteSettings = {
  address: 'Haagse uitweg 1A',
  addressCity: '4021 GB Buurmalsen',
  phone: '+31 (0)345 61 23 45',
  phoneHref: 'tel:+31345612345',
  email: 'info@dmkantoorinrichtingen.nl',
  footerDescription: 'Strategisch adviseur voor gezonde, duurzame en toekomstbestendige kantoorinrichtingen. Al meer dan 25 jaar de partner voor inspirerende werkomgevingen.',
  openingHours: [
    { id: '1', day: 'Maandag – vrijdag', hours: '09:00 – 17:30' },
    { id: '2', day: 'Zaterdag', hours: '10:00 – 16:00' },
    { id: '3', day: 'Zondag', hours: 'Gesloten' },
  ],
  socialLinkedin: 'https://linkedin.com',
  socialInstagram: 'https://instagram.com',
  socialFacebook: 'https://facebook.com',
  stats: [
    { id: '1', value: '500+', label: 'Projecten gerealiseerd' },
    { id: '2', value: '25+', label: 'Jaar ervaring' },
    { id: '3', value: '9.2', label: 'Klantwaardering' },
    { id: '4', value: '100%', label: 'Circulair inzicht' },
  ],
  showroomUSPs: [
    { id: '1', icon: 'Sofa', title: '500+ merken uitgestald', description: 'De grootste collectie kantoormeubelen van Nederland onder één dak.' },
    { id: '2', icon: 'Eye', title: 'Inspirerende sfeerhoeken', description: 'Ervaar zelf hoe verschillende inrichtingsstijlen aanvoelen in de praktijk.' },
    { id: '3', icon: 'Award', title: 'Gecertificeerde ergonomen', description: 'Persoonlijk advies van onze gecertificeerde werkplekergonomen.' },
    { id: '4', icon: 'Leaf', title: 'Duurzame collectie', description: 'Uitsluitend circulaire en verantwoord geproduceerde meubelcollecties.' },
  ],
  mapsUrl: 'https://maps.google.com/?q=Haagse+uitweg+1A,+4021+GB+Buurmalsen',
  showroomPageHeading: 'Onze showroom in Buurmalsen',
  showroomPageSubtitle: 'Kom langs en laat u inspireren. Meer dan 2.000 m² aan kantoorinrichting op één locatie, midden in het Rivierenland.',
  showroomSectionHeading: 'Waarom onze showroom bezoeken?',
  showroomCtaHeading: 'Plan uw bezoek aan de showroom',
  showroomCtaText: 'Maak een afspraak voor een persoonlijke rondleiding met één van onze adviseurs. Wij nemen ruim de tijd voor u.',
  seoShowroomTitle: 'Showroom Buurmalsen | DM Kantoorinrichtingen',
  seoShowroomDescription: 'Bezoek onze showroom in Buurmalsen — meer dan 2.000 m² kantoorinrichting. Laat u inspireren en ontvang persoonlijk advies van onze ergonomen.',
  seoContactTitle: 'Contact | DM Kantoorinrichtingen',
  seoContactDescription: 'Neem contact op met DM Kantoorinrichtingen. Bezoek onze showroom in Buurmalsen of stuur ons een bericht voor een vrijblijvend adviesgesprek.',
};

export const mockHomeContent: HomeContent = {
  heroHeading: 'Kantoorinrichtingen die uw team laten floreren',
  heroSubtitle: 'Gezonde, duurzame en toekomstbestendige werkomgevingen. Van strategisch advies tot complete realisatie.',
  heroLabel: 'Strategisch Kantooradviseur',
  heroPrimaryButtonLabel: 'Plan een adviesgesprek',
  heroSecondaryButtonLabel: 'Bekijk onze projecten',
  aanpakSteps: [
    { id: '1', number: '01', title: 'Kennismaking', description: 'We leren uw organisatie, werkwijze en ambities kennen in een vrijblijvend gesprek.' },
    { id: '2', number: '02', title: 'Analyse', description: 'Grondig onderzoek naar ruimtegebruik, werkpatronen en behoeften van uw team.' },
    { id: '3', number: '03', title: 'Concept', description: 'Een visueel en functioneel ontwerp dat uw identiteit en doelstellingen weerspiegelt.' },
    { id: '4', number: '04', title: 'Realisatie', description: 'Strakke projectbegeleiding van levering en plaatsing tot nazorg.' },
    { id: '5', number: '05', title: 'Oplevering', description: 'Uw nieuwe kantoor: op tijd, binnen budget, precies zoals besproken.' },
  ],
  duurzaamheidLabel: 'Onze belofte',
  duurzaamheidHeading: 'Duurzaam & gezond, dat is geen keuze maar een verplichting',
  duurzaamheidText: 'Wij geloven dat gezonde werkplekken en duurzame materialenkeuzen hand in hand gaan. Elk project dat wij realiseren draagt bij aan een betere wereld én een gezonder team.',
  duurzaamheidChecklist: [
    { id: '1', text: 'Gecertificeerde ergonomische werkplekken' },
    { id: '2', text: 'BREEAM & WELL certificering support' },
    { id: '3', text: 'Circulair hergebruik van bestaand meubilair' },
    { id: '4', text: 'CO₂-neutrale levering en installatie' },
    { id: '5', text: 'Uitsluitend A-merk, duurzaam geproduceerd' },
  ],
  contactCtaHeading: 'Laten we kennismaken',
  contactCtaText: 'Vertel ons over uw ruimte en wensen. We plannen graag een vrijblijvend gesprek en denken direct mee over de mogelijkheden.',
  aboutVisieHeading: 'Een werkplek is meer dan vier muren en een bureau',
  companyDescription1: 'Opgericht in 1999 door Dirk Martens vanuit een passie voor gezonde werkomgevingen, groeide DM Kantoorinrichtingen uit tot een toonaangevend adviesbureau voor kantoorinrichting in Nederland.',
  companyDescription2: 'Wij combineren strategisch inzicht met oog voor detail. Van de eerste analyse tot de sleuteloverhandiging — wij zorgen dat elke ruimte bijdraagt aan de doelstellingen van uw organisatie en het welzijn van uw medewerkers.',
  waarden: [
    { id: '1', title: 'Gezond werken', description: 'Wij geloven dat een gezonde werkplek de basis is voor een bloeiende organisatie.' },
    { id: '2', title: 'Duurzaam denken', description: 'Elke keuze die wij maken weegt de impact op mens en milieu mee.' },
    { id: '3', title: 'Eerlijk advies', description: 'Wij adviseren wat écht past bij uw organisatie, niet wat het meest lucratief is.' },
    { id: '4', title: 'Lange termijn', description: 'We bouwen relaties voor de lange termijn, niet voor een eenmalig project.' },
  ],
  aboutPageHeading: 'Over DM Kantoorinrichtingen',
  aboutPageSubtitle: 'Al meer dan 25 jaar de vertrouwde partner voor professionele kantoorinrichtingen in Nederland.',
  aboutTeamHeading: 'De mensen achter DM',
  aboutTeamSubtitle: 'Een gedreven team van adviseurs, designers en projectmanagers met passie voor inspirerende werkomgevingen.',
  seoHomeTitle: 'DM Kantoorinrichtingen — Professionele Kantoorinrichting',
  seoHomeDescription: 'Meer dan 25 jaar ervaring in professionele kantoorinrichting. Van strategisch advies tot complete inrichting. Gevestigd in Buurmalsen, actief door heel Nederland.',
  seoAboutTitle: 'Over Ons | DM Kantoorinrichtingen',
  seoAboutDescription: 'Leer meer over DM Kantoorinrichtingen — meer dan 25 jaar ervaring, een gepassioneerd team en een duurzame visie op kantoorinrichting.',
};
